name: Build and Release

on:
  schedule:
    - cron: '0 */2 * * *'
  repository_dispatch:
    types: [release]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-and-build:
    runs-on: ubuntu-slim
    concurrency:
      group: build-group
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Check for new version
        id: check
        run: python buildscripts/ci/get_version_status.py

      - name: Install uv
        if: steps.check.outputs.updated == 'true'
        uses: astral-sh/setup-uv@v7

      - name: Execute build sequence
        if: steps.check.outputs.updated == 'true'
        run: |
          uv sync --dev
          chmod +x buildscripts/*.sh
          python3 buildscripts/get_download_tag.py --save --tag ${{ steps.check.outputs.tag }}
          python3 buildscripts/update_project_version.py --tag ${{ steps.check.outputs.tag }}
          python3 buildscripts/download.py --build ubuntu-x64-vulkan
          ./buildscripts/extract_and_build_linux_x64.sh
          python3 buildscripts/download.py --build win-x64-vulkan
          ./buildscripts/extract_and_build_windows_x64.sh
          python3 buildscripts/download.py --build macos-arm64
          ./buildscripts/extract_and_build_macos_arm64.sh

      - name: Commit and Push changes
        if: steps.check.outputs.updated == 'true'
        run: |
          git config --local user.email "165793994+mdjou@users.noreply.github.com"
          git config --local user.name "Mykola Dzhus"
          git add src/lcpp_lib/__version__.py
          git commit -m "update version to ${{ steps.check.outputs.version }}"
          git push

      - name: Create GitHub Release
        if: steps.check.outputs.updated == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.check.outputs.version }}"
          name: "Release ${{ steps.check.outputs.version }}"
          body: "Wheels of llama.cpp version [${{ steps.check.outputs.tag }}](https://github.com/ggml-org/llama.cpp/releases/tag/${{ steps.check.outputs.tag }})"
          files: wheels/*.whl
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
